---

################################
# Reference:
#* https://docs.github.com/articles/generating-an-ssh-key/
#* https://docs.github.com/ssh-issues/
#* https://confluence.atlassian.com/bitbucket/set-up-ssh-for-git-728138079.html
#* https://confluence.atlassian.com/bitbucket/use-the-ssh-protocol-with-bitbucket-cloud-221449711.html
#* https://confluence.atlassian.com/bitbucket/configure-multiple-ssh-identities-for-gitbash-mac-osx-linux-271943168.html
################################

################################
# GITLAB_PERSONAL_USERNAME
################################

- name: Setting ansible variable 'gitssh_gitlab_user_name' from 'GITLAB_PERSONAL_USERNAME' env variable
  set_fact:
    gitssh_gitlab_user_name: "{{ lookup('ansible.builtin.env', 'GITLAB_PERSONAL_USERNAME', default=Undefined) }}"

- name: Fail if env variable 'GITLAB_PERSONAL_USERNAME' is not defined
  fail: msg="Environment Variable GITLAB_PERSONAL_USERNAME is not defined in your shell. Please set it and then try this ansible playbook again."
  when: gitssh_gitlab_user_name is undefined

################################
# CREATE DIR HOME/.gitssh
################################

- name: Creating 'HOME/.gitssh' directory with proper permissions
  file:
    path: "{{ ansible_facts['user_dir'] }}/.gitssh"
    state: directory
    #TODO: Set owner and group based on ansible_facts?
    #owner: username
    #group: groupname
    mode: 0700

################################
# GENERATE GITLAB SSH KEYPAIR (AS REQUIRED)
################################

- name: Check if ssh-keypair 'gitlab-{{ gitssh_gitlab_user_name }}' exists in 'HOME/.gitssh'
  stat:
    path: "{{ ansible_facts['user_dir'] }}/.gitssh/gitlab-{{ gitssh_gitlab_user_name }}"
  register: gitssh_gitlab_key_check

- name: Generate 'gitlab-{{ gitssh_gitlab_user_name }}' ssh-key in 'HOME/.gitssh if it does not exist yet'
  shell: 'ssh-keygen -t rsa -b 4096 -f $HOME/.gitssh/gitlab-{{ gitssh_gitlab_user_name }} -q -N ""'
  when:
    - not gitssh_gitlab_key_check.stat.exists

################################
# UPDATE SHELL_RCFILE AND HOME/.ssh/config
################################

- name: Insert/Update config lines in 'HOME/{{ shell_rcfile }}' for ssh-add to load ssh-key 'gitlab-{{ gitssh_gitlab_user_name }}' into SSH keyring
  ansible.builtin.blockinfile:
    path: "{{ ansible_facts['user_dir'] }}/{{ shell_rcfile }}"
    marker: "{mark}"
    marker_begin: "#----------[gitssh-gitlab]---ANSIBLE MANAGED BLOCK---BEGIN"
    marker_end:   "#----------[gitssh-gitlab]---ANSIBLE MANAGED BLOCK---END"
    backup: yes
    block: |
      # Add gitlab SSH key to SSH Keyring
      ssh-add $HOME/.gitssh/gitlab-{{ gitssh_gitlab_user_name }} > /dev/null 2>&1

- name: Insert/Update config lines in 'HOME/.ssh/config' for Hostname 'gitlab.com'
  ansible.builtin.blockinfile:
    path: "{{ ansible_facts['user_dir'] }}/.ssh/config"
    marker: "{mark}"
    marker_begin: "#----------[gitssh-gitlab]---ANSIBLE MANAGED BLOCK---BEGIN"
    marker_end:   "#----------[gitssh-gitlab]---ANSIBLE MANAGED BLOCK---END"
    backup: yes
    block: |
      Host {{ gitssh_gitlab_user_name }}.gitlab.com
          HostName gitlab.com
          User git
          IdentityFile {{ ansible_facts['user_dir'] }}/.gitssh/gitlab-{{ gitssh_gitlab_user_name }}

################################
# GITLAB_TOKEN_HTTPS - SET GIT GLOBAL CONFIG url.<> insteadOf <> for terraform to use GITLAB TOKEN for getting modules from gitlab
################################

#- name: Setting ansible variable 'gitssh_gitlab_token_https' from 'GITLAB_TOKEN_HTTPS' env variable if it is set in SHELL
#  set_fact:
#    gitssh_gitlab_token_https: "{{ lookup('ansible.builtin.env', 'GITLAB_TOKEN_HTTPS', default=Undefined) }}"

#- name: Set git global config url.'https://${GITLAB_TOKEN_HTTPS}@gitlab.com'.insteadOf 'https://gitlab.com' only if 'GITLAB_TOKEN_HTTPS' env variable is set in SHELL
#  shell: |
#    if [[ -z $GITLAB_TOKEN_HTTPS ]];then
#      echo "GITLAB_TOKEN_HTTPS is not set in shell - doing nothing"
#    else
#      ### Print out existing git global config
#      echo "" ; echo "Current git global config:" ; echo ""
#      git config --global --list
#      ### UnSetting git global config for url. insteadOf "https://gitlab.com"
#      GIT_CONFIG_EXISTING_URL_INSTEADOF=$(git config --global --list |grep "url." |grep '.insteadof=https://gitlab.com' |awk -F 'url.' '{print $2}' |awk -F '.insteadof' '{print $1}' )
#      git config --global --unset url."${GIT_CONFIG_EXISTING_URL_INSTEADOF}".insteadOf "https://gitlab.com"
#      ### Setting git global config
#      git config --global url."https://${GITLAB_TOKEN_HTTPS}@gitlab.com".insteadOf "https://gitlab.com"
#      chmod 600 $HOME/.gitconfig # Secure global git config so nobody except authenticated user can read its contents
#      ### Print out newly set git global config
#      echo "" ; echo "Adjusted git global config:" ; echo ""
#      git config --global --list
#      echo ""
#    fi
#
#- name: Unset 'GITLAB_TOKEN_HTTPS' env variable from SHELL
#  shell: "unset GITLAB_TOKEN_HTTPS"
